import type { Candidate } from './types';

export const candidates: Candidate[] = [
  {
    id: 'benhur-abalos',
    fullName: 'Benjamin "Benhur" Abalos Jr.',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'bam-aquino',
    fullName: 'Paolo Benigno "Bam" Aquino IV',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'abby-binay',
    fullName: 'Mar-len Abigail "Abby" Binay',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'pia-cayetano',
    fullName: 'Pia Cayetano',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ronald-dela-rosa',
    fullName: 'Ronald "Bato" Dela Rosa',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'christopher-go',
    fullName: 'Christopher "Bong" Go',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ping-lacson',
    fullName: 'Panfilo "Ping" Lacson',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'imee-marcos',
    fullName: 'Imee Marcos',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'manny-pacquiao',
    fullName: 'Emmanuel "Manny" Pacquiao',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'tito-sotto',
    fullName: 'Vicente "Tito" Sotto III',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ramon-revilla-jr',
    fullName: 'Ramon "Bong" Revilla Jr.',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'bonifacio-bosita',
    fullName: 'Bonifacio Bosita',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'arlene-brosas',
    fullName: 'Arlene Brosas',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'roy-cabonegro',
    fullName: 'Roy Cabonegro',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'allen-capuyan',
    fullName: 'Allen Capuyan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'teddy-casino',
    fullName: 'Teodoro "Teddy" Casiño',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'francisca-castro',
    fullName: 'Francisca "France" Castro',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'angelo-de-alban',
    fullName: 'Angelo De Alban',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'david-dangelo',
    fullName: "David D'Angelo",
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'leody-de-guzman',
    fullName: 'Leodegario "Leody" De Guzman',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'gregorio-honasan',
    fullName: 'Gregorio "Gringo" Honasan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'relly-jose-jr',
    fullName: 'Relly Jose Jr.',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'raul-lambino',
    fullName: 'Raul Lambino',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'manuel-lapid',
    fullName: 'Manuel "Lito" Lapid',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'wilbert-lee',
    fullName: 'Wilbert Lee',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'amirah-lidasan',
    fullName: 'Amirah Lidasan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'rodante-marcoleta',
    fullName: 'Rodante Marcoleta',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'norman-marquez',
    fullName: 'Norman Marquez',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'eric-martinez',
    fullName: 'Eric Martinez',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'richard-mata',
    fullName: 'Richard Mata',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jose-matula',
    fullName: 'Jose "Sonny" Gito Matula',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'liza-maza',
    fullName: 'Liza Largoza Maza',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'heidi-mendoza',
    fullName: 'Heidi Lloce Mendoza',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jose-montemayor-jr',
    fullName: 'Jose Jr. Cabrera Montemayor',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jose-jessei-olivar',
    fullName: 'Jose Jessei Dela Calsada Olivar',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'willie-ong',
    fullName: 'Willie Tan Ong',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'kiko-pangilinan',
    fullName: 'Francis "Kiko" Pangilinan',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id:'ariel-querubin',
    fullName: 'Ariel Porfirio Oliva Querubin',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'apollo-quiboloy',
    fullName: 'Apollo Carreon Quiboloy',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'danilo-ramos',
    fullName: 'Danilo Hernandez Ramos',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'willie-revillame',
    fullName: 'Wilfredo "Willie" Revillame',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'vic-rodriguez',
    fullName: 'Victor "Vic" Rodriguez',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'nur-ana-sahidulla',
    fullName: 'Nur-Ana Indanan Sahidulla',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'phillip-salvador',
    fullName: 'Phillip Reyes Salvador',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'chavit-singson',
    fullName: 'Luis "Chavit" Singson',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'michael-tapado',
    fullName: 'Michael Balais Tapado',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'francis-tolentino',
    fullName: 'Francis Ng Tolentino',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ben-tulfo',
    fullName: 'Bienvenido "Ben" Teshiba Tulfo',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'erwin-tulfo',
    fullName: 'Erwin Teshiba Tulfo',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'mario-valbuena',
    fullName: 'Mario Jr. "Mar" Soliven Valbuena',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'leandro-verceles',
    fullName: 'Leandro Buenconsejo Verceles',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'camille-villar',
    fullName: 'Camille Aguilar Villar',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ronaldo-adonis',
    fullName: 'Ronaldo Mangampo Adonis',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'wilson-amad',
    fullName: 'Wilson Caritero Amad',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jocelyn-andamo',
    fullName: 'Jocelyn Santos Andamo',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ronnel-arambulo',
    fullName: 'Ronnel Gondraneos Arambulo',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'ernesto-arellano',
    fullName: 'Ernesto Rillera Arellano',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'roberto-ballon',
    fullName: 'Roberto Amido Ballon',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'jimmy-bondoc',
    fullName: 'James Patrick "Jimmy" Romero Bondoc',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  },
  {
    id: 'mimi-doringo',
    fullName: 'Eufemia "Mimi" Pet Doringo',
    positionSought: 'Senator',
    politicalAffiliation: 'Unknown',
    imageUrlId: '',
    education: [],
    careerTimeline: [],
    platforms: [],
    controversies: [],
    promises: [],
  }
];
